import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#6366f1' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 50,
    paddingBottom: 20,
    paddingHorizontal: 20,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: { fontSize: 20, fontWeight: '600', color: '#ffffff' },
  content: {
    flex: 1,
    backgroundColor: '#f9fafb',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingTop: 40,
    alignItems: 'center',
  },
  instruction: { fontSize: 24, fontWeight: '600', color: '#1f2937', marginBottom: 40 },
  numberSection: { marginBottom: 40 },
  placeholder: { width: 40 },
  placeholderText: { fontSize: 96, fontWeight: 'bold', color: '#d1d5db' },
  stats: { flexDirection: 'row', gap: 16, marginBottom: 32 },
  statCard: {
    backgroundColor: '#ffffff',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 16,
    alignItems: 'center',
    elevation: 5,
  },
  statLabel: { fontSize: 14, color: '#6b7280', marginBottom: 4 },
  statValue: { fontSize: 24, fontWeight: 'bold', color: '#6366f1' },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#eef2ff',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginHorizontal: 20,
    gap: 12,
  },
  infoText: { flex: 1, fontSize: 14, color: '#4f46e5' },
});